### ISSUE TITLE
Can't create function if too many parameters are specified

### ISSUE THREAD

**Issue by sfc-gh-gcharriere** [Snowflake-Labs/snowflake-cli#72]
Function creation fails if too many parameters are specified. This issue seems to be linked to a limited number of character supported in the IMPORTS statement of the UDF.

As you can see in the image, snowcli adds all the names and types specified as function parameter in the path where the application is zipped.
@ML_PROVIDER.APP.deployments/f_scoresf_string_rf_float_dd_float_pl_float_es_float_er_float_ec_number_ao_number_dblfd_number_dbfcd_number_fddf_number_fddm_number_fddsa_number_fddsu_number_fddth_number_fddtu_number_fddw_number_ca_number_cd_number_ch_number_cw_number/app.zip

Adding more input parameters adds more characters to the Import path. At some point, the function cannot be created.

![Screenshot 2023-01-31 at 16 01 24](https://user-images.githubusercontent.com/83585274/215796336-61c7b324-87a1-4d70-9928-38e322f631e5.png)

**Comment by jeffhollan** [comment]
Ah makes sense. Right now the logic creates a stage for each function and uses the input Params to name it (so myfunc(number, string) and myfunc(number) would have two stages). But this shows that limitation. I'll look at changing the logic to have some way to generate mostly unique stage names without hitting this character limit

**Comment by py-prash** [comment]
Related to this issue, the describe function (post create) fails for multiple input parameters. Its failing because the generate signature method (generate_signature_from_params(params: str) is not retrieving the data types correctly for the describe function. The split function in  the method would need to be rewritten as something like below : 
"(" + ",".join(" ".join(input_str.split(',')).split(' ')[1::2])

**Comment by sfc-gh-astus** [comment]
Fixed in 2.0.0
